name: youtube_explode_dart
description: A port in dart of the youtube explode library. Support serveral API functions.
version: 0.0.2
homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  http: ^0.12.0+4

dev_dependencies:
  effective_dart: ^1.2.1
  dart_console: ^0.5.0
  test: ^1.12.0